// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jayfyarydzkycjzciblj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpheWZ5YXJ5ZHpreWNqemNpYmxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTE4ODksImV4cCI6MjA2NjI4Nzg4OX0.Haq3hDHxPTBdIVoHVuTa_moX8BJUVoWyV2J5mRSlDeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);